package com.bockmedia.console.ui.testing

/** Stable Compose test tags for instrumented UI / perf audits (debug builds). */
object BockTestTags {
    const val BOTTOM_NAV = "bock_bottom_nav"
    const val NAV_HOME = "bock_nav_home"
    const val NAV_SEARCH = "bock_nav_search"
    const val NAV_LIBRARY = "bock_nav_library"
    const val NAV_DOWNLOADS = "bock_nav_downloads"
    const val NAV_AUTOMATIONS = "bock_nav_automations"

    const val SCREEN_LOADING = "bock_screen_loading"
    const val HOME_FEED = "bock_home_feed"
    const val HOME_GREETING = "bock_home_greeting"
    const val TAB_HEADER = "bock_tab_header"
    const val SEARCH_FIELD = "bock_search_field"
    const val SEARCH_RESULTS = "bock_search_results"
    const val SEARCH_BROWSE_GRID = "bock_search_browse_grid"
    const val SEARCH_RESULT_ROW = "bock_search_result_row"
    const val LIBRARY_LIST = "bock_library_list"
    const val AUTOMATIONS_CONTENT = "bock_automations_content"
    const val ANALYTICS_BODY = "bock_analytics_body"
    const val ANALYTICS_TOTAL_PLAYS = "bock_analytics_total_plays"
    const val ACCOUNT_MENU = "bock_account_menu"
    const val ACCOUNT_MENU_BUTTON = "bock_account_menu_button"
    const val SETTINGS_BODY = "bock_settings_body"
    const val SETTINGS_WIFI_ONLY = "bock_settings_wifi_only"
    fun settingsContinue(value: String) = "bock_settings_continue_$value"
    const val FAMILY_ACTING_AS = "bock_family_acting_as"
    const val FAMILY_BODY = "bock_family_body"
    const val SPLASH = "bock_splash"
    const val SETUP_SCREEN = "bock_setup_screen"
    const val PROFILE_PICKER = "bock_profile_picker"
    const val PROFILE_CONTINUE_UNATTRIBUTED = "bock_profile_continue_unattributed"

    const val PLAYLIST_DETAIL_BODY = "bock_playlist_detail_body"
    const val ARTIST_DETAIL_BODY = "bock_artist_detail_body"
    const val ALBUM_DETAIL_BODY = "bock_album_detail_body"
    const val GENRE_DETAIL_BODY = "bock_genre_detail_body"
    const val NOW_PLAYING_BODY = "bock_now_playing_body"
    const val NOW_PLAYING_PLAY_PAUSE = "bock_now_playing_play_pause"
    const val NOW_PLAYING_QUEUE = "bock_now_playing_queue"
    const val DOWNLOADS_LIST = "bock_downloads_list"
    const val DOWNLOAD_COLLECTION_ROW = "bock_download_collection_row"
    const val DOWNLOAD_DETAIL_BODY = "bock_download_detail_body"
    const val DEVICE_PICKER_SHEET = "bock_device_picker_sheet"
    const val DEVICE_PICKER_LOCAL_PHONE = "bock_device_picker_local_phone"
    const val MIXMUSE_SHEET = "bock_mixmuse_sheet"
    const val DISCOVERY_MENU = "bock_discovery_menu"
    const val LISTEN_AGENT_BODY = "bock_listen_agent_body"
    const val AUTOMATION_ROW = "bock_automation_row"
    const val AUTOMATION_FORM = "bock_automation_form"
    const val ROOMS_BODY = "bock_rooms_body"
    const val DEVICES_BODY = "bock_devices_body"
    const val VOICE_LOG_BODY = "bock_voice_log_body"
    const val DRIVING_BODY = "bock_driving_body"
    const val ABOUT_BODY = "bock_about_body"
    const val ROUTINES_BODY = "bock_routines_body"
    const val FAVORITES_BODY = "bock_favorites_body"
    const val PLAYLISTS_LIST_BODY = "bock_playlists_list_body"
    const val ARTISTS_LIST_BODY = "bock_artists_list_body"
    const val ALBUMS_LIST_BODY = "bock_albums_list_body"
    const val SONGS_LIST_BODY = "bock_songs_list_body"
    const val CLIENT_ID = "bock_client_id"

    fun homeSection(id: String) = "bock_home_section_$id"
    fun homeFilter(name: String) = "bock_home_filter_$name"
    fun profileMemberPick(id: String) = "bock_profile_member_$id"
}
